version: "3.8"

services:
  check:
    image: abogoyavlensky/clojure-openjdk11-build:0.1.3
    volumes:
      - .:/app

  marked:
    build: docker/marked
    working_dir: /app
    volumes:
      - .:/app
