name: CI


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: docker compose run --rm check bash -c "make lint-init > /dev/null 2>&1 || true && make lint"

      - name: Fmt
        run: docker compose run --rm check make fmt-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: docker compose run --rm check bash -c "make test-ci"
        