name: CI


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Clojure deps
        run: clj -Spath

      - name: Lint
        run: make lint-init

      - name: Fmt
        run: make fmt-check
