name: CI


on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Clojure tools.deps
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.1.561.sh
          chmod +x linux-install-1.10.1.561.sh
          ./linux-install-1.10.1.561.sh

      - name: Install Clojure deps
        run: clj -Spath

      - name: Lint
        run: make lint-init

      - name: Fmt
        run: make fmt-check
